### ISSUE TITLE
what happened?

### ISSUE THREAD

**Issue by githubUser982** [jmesfo0/RitaBot#1]
Just wondering if you know what happened to the ritabot project, since its gone now.

**Comment by jmesfo0** [comment]
it's a paid bot now. sellouts

**Comment by githubUser982** [comment]
Jeez what a shame. Well, they were awful to me when trying to report and fix one of their bugs... So no surprise.
They even made you fork before they'd look at your issue. I'm guessing to look more popular?

**Comment by githubUser982** [comment]
Thank you though!!

**Comment by jmesfo0** [comment]
you're quite welcome!
